### ISSUE TITLE
Online Help Optional [was: cannot compile without qt5webenginewidgets]

### ISSUE THREAD

**Issue by matevz** [canorusmusic/canorus#110]
Raspbian and probably debian don't provide qt5webenginewidgets anymore. I get
```
CMake Warning at CMakeLists.txt:102 (FIND_PACKAGE):
  By not providing "FindQt5WebEngineWidgets.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5WebEngineWidgets", but CMake did not find one.

  Could not find a package configuration file provided by
  "Qt5WebEngineWidgets" with any of the following names:

    Qt5WebEngineWidgetsConfig.cmake
    qt5webenginewidgets-config.cmake

  Add the installation prefix of "Qt5WebEngineWidgets" to CMAKE_PREFIX_PATH
  or set "Qt5WebEngineWidgets_DIR" to a directory containing one of the above
  files.  If "Qt5WebEngineWidgets" provides a separate development package or
  SDK, be sure it has been installed.
```
and package `qtwebengine5-dev` does not exist.

Make this package optional or remove built-in help.

**Comment by matevz** [comment]
Oops, this is just a warning. Makefile is still produced and canorus can be built without support for built-in help browser.

**Comment by suamor** [comment]
I don't believe this. Webengine is an too essential Qt component to remove it. I'm sure it was either renamed or moved to a different repository like universe or multiverse. 
Do you have any concrete information why this should have been removed ?
The documentation is essential for Canorus. It is not an optional dependency.

We could only think about providing an alternative way to display it. However this would just create another dependency. For Qt this would probably be the assistant interface (used by QtCreator to my knowledge).

I checked Qt webpages and found no hints or plans that it will be removed. It is part of both Qt5.12 as well as Qt5.13.

**Comment by matevz** [comment]
Ubuntu and Debian provide `qtwebengine5` libraries and dev packages fine. Current raspbian's `qtwebengine` though is broken. For example, you cannot even install `qutebrowser-qtwebengine`, because it doesn't provide `libqt5webenginecore5`. You can, however, install `qutebrowser-qtwebkit`.

So I wouldn't bother much with this, because a fallback is simply showing the help in external application (`QDesktop` call on .html file). Usually a web browser just pops up for opening the user's guide which seems ok. This is also the case for raspberry.

**Comment by matevz** [comment]
@suamor If this answers your question, please close the issue.

**Comment by suamor** [comment]
Ok, I hope this will be fixed.
