### ISSUE TITLE
canorus crashes on exit

### ISSUE THREAD

**Issue by matevz** [canorusmusic/canorus#120]
When python support is compiled in, Canorus crashes on exit with random errors like:
* `double free or corruption (out)`
* `double free or corruption (!prev)`
* `free(): invalid pointer`

This is always reproducible on any operating system.

**Comment by suamor** [comment]
In my experience this only happens with python plugins enabled.

**Comment by suamor** [comment]
My branch shows the message "corrupted size vs. prev_size" before crashing. 
Stackoverflow discussion on this:
https://stackoverflow.com/questions/49628615/understanding-corrupted-size-vs-prev-size-glibc-error
This was just a quick test if anything obviously not working with my changes applied.

**Comment by matevz** [comment]
Those errors are very tricky. For me it shows a different segfault location each time it crashes. IMO it's a python-releated crash on the same object being freed twice, possibly because of the thread (maybe some missing mutex lock somwhere in destructors?)..

**Comment by matevz** [comment]
This might be solved once we use smart pointers accross the code (#133).

**Comment by suamor** [comment]
PR #158 may fix this issue, please check and report back.
