### ISSUE TITLE
Issues with some translation not updated

### ISSUE THREAD

**Issue by suamor** [canorusmusic/canorus#121]
I'm still on a different branch doing fixes on warnings.
I noticed that the qt translator complains about several ts files not updated:

"It contains translation but the target language is not recognized".

This concerns danish, french, hungarian, swahili. 
To my memory except french we do not have any translations for those languages at all.

**Comment by matevz** [comment]
Is this related to https://github.com/canorusmusic/canorus/issues/51 I recently fixed?

**Comment by suamor** [comment]
No, though I cannot check that issue. This one looks to be about the language itself and the other one about the translation generation. Which Qt version are you using ? I have not updated my 5.12 for some time.

Note that I generate the translations differently as presented in the other issue due to an langauge installation issue.

**Comment by matevz** [comment]
Did you try running `make tr`? This calls lupdate. And just running `make` calls lrelease.

**Comment by matevz** [comment]
Check https://github.com/canorusmusic/canorus/issues/51#issuecomment-570784344

**Comment by suamor** [comment]
make tr works.

**Comment by suamor** [comment]
Fixed with b4aef9797c522d556383d32dfd7559e673ecad71
