### ISSUE TITLE
Incorrect baseline committed with Volta changes

### ISSUE THREAD

**Issue by suamor** [canorusmusic/canorus#131]
Master is building. But it misses parts or everything of the chordname implementation (or maybe more).
Latest changes for volta removed of older code.
I checked CMakeLists.txt and this is from an older baseline.

**Comment by suamor** [comment]
I'm not sure what happened to the Chord changes but at least building works.

**Comment by suamor** [comment]
I do not see changes of it but when I check the repository of the volta change the Chordname changes are missing. 
I suppose that the baseline of the volta branch is now in master...

**Comment by suamor** [comment]
I will try to revert the volta change locally to test if this will restore the correct master baseline.
Cherry-picking the commits is no fun...

**Comment by matevz** [comment]
> I'm not sure what happened to the Chord changes but at least building works.

I think you didn't correctly revert @itsgeorg's merge commit, otherwise it should be there.

**Comment by suamor** [comment]
I reverted with github tool. If that did not work, there is a bug in the tool.

**Comment by suamor** [comment]
Guys, please make a backup of your files.
I could not reach Georg, so I will do the following:
1) Revert Volta changes
2) Check if baseline is res Stored
2a) if not remove all changes from master since then 
    (I also will make a local backup just in case before)
3) Switch to volta branch
4) Merge master changes with that branch
5) Create pull request.

In future please always create pull requests to avoid these kind of desasters.

**Comment by matevz** [comment]
IMO I would just checkout 9d52a34 and then apply cbee22f and e59c901. Compare the obtained content with the current master and push the difference.

**Comment by suamor** [comment]
Update: 
1. done, but 2. baseline was not restord 3 + 4 done
2a) not done, will check these commits first.

**Comment by suamor** [comment]
Commit was pushed. https://github.com/canorusmusic/canorus/commit/13896752b0cb48cdb11ace48cbbb7962bf41a2bc
