### ISSUE TITLE
Build failure: Canorus Python Plugin

### ISSUE THREAD

**Issue by suamor** [canorusmusic/canorus#163]
On Ubuntu 20.04 with python 3.8 the plugin fails to build:
`66/366 3.8/sec] Building CXX object src/CMakeFiles/CanorusPython.dir/canoruspythonPYTHON_wrap.cxx.o
FAILED: src/CMakeFiles/CanorusPython.dir/canoruspythonPYTHON_wrap.cxx.o 
/usr/bin/clang++  -DCANORUS_VERSION=\"0.8.0rc1\" -DCanorusPython_EXPORTS -DDEFAULT_DATA_DIR=\"/media/suamor/home/home/suamor/projekte/canorus/gh/build-canorus-Desktop_Qt_5_12_8_Clang_64bit-Debug/install/share/canorus\" -DQT_CORE_LIB -DQT_GUI_LIB -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DUSE_PYTHON -DUSE_SWIG -D__LINUX_ALSA__ -I/home/suamor/projekte/canorus/gh/canorus/src -I/home/suamor/projekte/canorus/gh/canorus/src/zlib -I/home/suamor/projekte/canorus/gh/canorus/src/core -I/home/suamor/projekte/canorus/gh/canorus/src/ui -I/home/suamor/projekte/canorus/gh/canorus/src/widgets -I/home/suamor/projekte/canorus/gh/canorus/src/import -Isrc -I/usr/include/python3.8 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -O0 -g -fstack-protector-all -Wall -Werror -Wuninitialized -Wtype-limits -Wstack-protector -fPIC   -DSWIGCPP -fPIC -std=gnu++14 -MD -MT src/CMakeFiles/CanorusPython.dir/canoruspythonPYTHON_wrap.cxx.o -MF src/CMakeFiles/CanorusPython.dir/canoruspythonPYTHON_wrap.cxx.o.d -o src/CMakeFiles/CanorusPython.dir/canoruspythonPYTHON_wrap.cxx.o -c src/canoruspythonPYTHON_wrap.cxx
In file included from src/canoruspythonPYTHON_wrap.cxx:179:
In file included from /usr/include/python3.8/Python.h:85:
In file included from /usr/include/python3.8/pytime.h:6:
In file included from /usr/include/python3.8/object.h:746:
/usr/include/python3.8/cpython/object.h:177:16: error: 'tp_print' is deprecated [-Werror,-Wdeprecated-declarations]
typedef struct _typeobject {
               ^
src/canoruspythonPYTHON_wrap.cxx:1768:23: note: in implicit copy assignment operator for '_typeobject' first required here
    swigpyobject_type = tmp;
                      ^
/usr/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
    Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
    ^
/usr/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))`

This is from generated code. I'm not sure what is the actual cause of it, but it looks more like an issue between installed components than an issue from Canorus. Any ideas ?
tp_print was not marked deprecated accidently and python 3.7 is not available (which I do not really understand, 3.6 is available, but I have found no info on this).

Issue cause is apparently:
cpython/object.h declares a member inside a struct as deprecated.
However this makes the whole struct deprecated.
Inside the canorus wrap code tp_print member is not used at all.

**Comment by matevz** [comment]
Swig version? I've beed using swig4 and it compiles fine.

**Comment by suamor** [comment]
swig 4.0.1

**Comment by suamor** [comment]
I tried adding 
`#define Py_DEPRECATED(VERSION_UNUSED)
`
However this is ignored even though swig documentation states these macros can be used.
Any ideas ?

**Comment by suamor** [comment]
I checked on swig and apparently it is already fixed:
https://github.com/swig/swig/pull/1670
As swig 4.0.2 is not yet released I reported Ubuntu to add it to 4.0.1 as patch.
https://bugs.launchpad.net/ubuntu/+source/swig/+bug/1876764

**Comment by suamor** [comment]
For MAC builds we either need to wait for swig 4.0.2 in homebrew or use python 3.7 if available.

**Comment by matevz** [comment]
Did you try compiling swig yourself and test whether it works with current swig master?

**Comment by suamor** [comment]
I built it, however this package want a private key from some maintainer.
I probably need to be a maintainer myself or change something so that it is no more a normal Ubuntu package (no experience with that though).

**Comment by suamor** [comment]
And bad luck for me.. the above patch-set does not fix the issue.. probably more needs to be patched in swig.

**Comment by suamor** [comment]
So there is one issue in our CMakeLists.txt file. It actually defines "Wno-error" but is defined before the file itself is defined. So the change on the compile options never gets applied.

The issue cause itself is discussed in here:
https://github.com/cython/cython/issues/3474

So you whatever you do you cannot get rid of this warning (error), though the "initializer" warning is less problematic (however it would need to be changed on swig side).

I will upload later a pull-request for the CMakeLists.txt changes.

**Comment by suamor** [comment]
Fixed with above pull request merged.
