### ISSUE TITLE
Thank you very much for the program!

### ISSUE THREAD

**Issue by mrkaban** [canorusmusic/canorus#180]
Thank you very much for the program released under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D1%81%D0%B8%D0%BD%D1%82%D0%B5%D0%B7/canorus-%D0%BD%D0%BE%D1%82%D0%BD%D1%8B%D0%B9-%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80.html).

Please do not abandon the project, this is a very interesting program!

Will the releases be published here? 

There will be no more assemblies for Windows?

**Comment by matevz** [comment]
Hi mrkaban. Thanks for the link.

Releases will be published on github, yes.

For Windows we are still setting up proper development environment. Docker image is now ready https://hub.docker.com/repository/docker/canorus/buildenv-windows, but we still need to integrate it into github CI for performing tests and automatically compile windows packages when a new release is made.
