### ISSUE TITLE
Cannot install on macOS Mojave

### ISSUE THREAD

**Issue by csarami** [canorusmusic/canorus#181]
Hi,

I tried to follow the installation. It seems the README file is old and I downloaded: canorus-0.7.3rc3.

` $ cmake .
CMake Error at CMakeLists.txt:94 (FIND_PACKAGE):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
`
I looked into the folder and I don't see any " Qt5CoreConfig.cmake" or "qt5core-config.cmake" files there! How can I fix this, please?

**Comment by matevz** [comment]
Hi csarami.

Did you download and install Qt5 for open source projects to your computer? Qt5CoreConfig.cmake is shipped along Qt5 and not cmake.

**Comment by csarami** [comment]
Thank you very much. I will give it a try.

**Comment by suamor** [comment]
I close this one as old (no further feedback received).
