### ISSUE TITLE
LilyPond 2.24.0

### ISSUE THREAD

**Issue by Jean-Abou-Samra** [canorusmusic/canorus#188]
Hi, opening an issue because I don't know where else to contact people from this project. LilyPond 2.24.0, a new stable version of LilyPond has been released. See https://lists.gnu.org/archive/html/lilypond-user/2022-12/msg00131.html for full information.

**Comment by matevz** [comment]
Thanks. I can confirm lilypond 2.24.0 works fine with Canorus-exported .ly files (after applying convert-ly).
