### ISSUE TITLE
Translation files at wrong location

### ISSUE THREAD

**Issue by matevz** [canorusmusic/canorus#51]
**Reported by alexl000 on 2019-04-19 05:06 UTC**
It does not create qm files. So localization is missing.

**Comment by matevz** [comment]
**Commented by alexl000 on 2019-04-19 05:29 UTC**
qm files were not installed

**Comment by matevz** [comment]
**Commented by alexl000 on 2019-04-22 05:45 UTC**
It's ok with the latest svn snapshot.

**Comment by matevz** [comment]
Steps to reproduce:
* pull canorus from git on a clean machine
* cmake . && make
* src/canorus

The translation is not there, because the generated .qm files should be in `src/lang` folder, but are just in `src/`.

**Comment by matevz** [comment]
I found out you can pass an output directory option to `qt5_add_translation()`. This now works as it should. Attached is the patch.

[lang_location.patch.txt](https://github.com/canorusmusic/canorus/files/3910172/lang_location.patch.txt)

**Comment by suamor** [comment]
This does not work for me. However I use a different way to generate translations, so maybe something is now overlapping. My problems were that the lang folder was not working during installation (not during build)

`ADD_CUSTOM_COMMAND(
	TARGET canorus
	PRE_BUILD
	WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/src
	COMMAND ${Qt5_LUPDATE_EXECUTABLE}
	ARGS -noobsolete ${Canorus_UIC_Srcs} ${Canorus_Srcs} -ts ${Canorus_Translation_Srcs} lang/template.ts -I. -Icore
)
#set_source_files_properties(${Canorus_Translation_Srcs} PROPERTIES OUTPUT_LOCATION "lang")
`
Error message I get is
`Updating 'lang/cs.qm'...
lrelease error: cannot create 'lang/cs.qm': No such file or directory
src/CMakeFiles/canorus_qm.dir/build.make:73: recipe for target 'src/lang/cs.qm' failed`

I'm not sure what to expect here. My build/src/lang folder contains the file. CMake issue?

**Comment by matevz** [comment]
Updating `some machine object file` seems very wrong. lupdate should be called on .ts files?

**Comment by suamor** [comment]
Even after executing "make tr" (with master changes integrated into my branch) I cannot build. I will now revert this change.

**Comment by suamor** [comment]
Ok the solution is: Create a folder src/lang in the build folder.

**Comment by suamor** [comment]
Fixed with above commit.
